# Copyright 2019 Intel Corporation and Smart-Edge.com, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Disable libvirt's DNS
  replace:
    path: /usr/share/libvirt/networks/default.xml
    regexp: '.*<dns>(\n.*){6}\n.*</dns>'
    replace: '  <dns enable="no"/>'

- virt_net:
    command: destroy
    name: default

- virt_net:
    command: undefine
    name: default

- name: Load DNS settings
  shell: virsh net-define /usr/share/libvirt/networks/default.xml

- virt_net:
    command: start
    name: default
    autostart: yes
    
- name: Change /etc/dnsmasq.conf
  blockinfile:
    path: /etc/dnsmasq.conf
    block: |
      strict-order
      except-interface=lo
      address=/eaa.community.appliance.mec/syslog.community.appliance.mec/192.168.122.1

- name: Enable dnsmasq service
  systemd:
    name: dnsmasq 
    enabled: yes
    masked: no
    state: restarted

- name: Setup Kubernetes DNS
  replace:
    path: /var/lib/kubelet/config.yaml
    regexp: '.*clusterDNS:\n- ([0-9]+\.){3}[0-9]+'
    replace: 'clusterDNS:\n- 192.168.122.1'
