# Copyright 2019 Intel Corporation and Smart-Edge.com, Inc. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3'
services:
  nts:
    container_name: nts
    build:
      context: .
      dockerfile: "Dockerfile_nts"
    image: "nts:${VER}"
    privileged: true
    volumes:
     - "/dev/hugepages:/hugepages"
     - "/var/lib/appliance/nts:/var/lib/appliance/nts"
     - "/var/run/docker/netns:/var/run/docker/netns"
     - "/var/run:/var/run"
     - "/proc/1/ns:/var/host_ns"
     - "/sys/class/net:/var/host_net_devices"
    environment:
     - NTS_SOCKET0_MEM=${NTS_MEM_MB_S0}
     - NTS_SOCKET1_MEM=${NTS_MEM_MB_S1}
     - OVS_BRIDGE_NAME=${OVS_BRIDGE_NAME}
     - OVS_ENABLED=${OVSE}
    network_mode: host
