# Copyright 2019 Intel Corporation and Smart-Edge.com, Inc. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# TODO: Expose ports only to a local network address
version: '3'
services:
  appliance:
    build:
      context: .
      dockerfile: "Dockerfile_appliance"
    image: "appliance:${VER}"
    privileged: true
    ports:
     - "42101:42101"
     - "42102:42102"
     - "443:443"
    volumes:
     - "/var/lib/nts:/var/lib/nts"
     - "/run:/run"
     - "/proc/1/ns:/var/host_ns:ro"
     - "/sys/class/net:/var/host_net_devices"
     - "/sys/devices:/devices"
     - "/var/lib/appliance/certs:/root/certs"
    networks:
      net:
        ipv4_address: 192.17.0.2
  edgednssvr:
    build:
      context: .
      dockerfile: "Dockerfile_edgednssvr"
    image: "edgednssvr:${VER}"
    ports:
     - "53:53/udp"
    volumes:
     - "/var/lib/appliance/edgednssvr:/var/lib/edgedns"
     - "/run:/run"
    environment:
     - http_proxy
     - https_proxy
     - DNS_FWDR=8.8.8.8
     - LOCAL_SYSLOG=192.17.0.5:514
    networks:
      net:
        ipv4_address: 192.17.0.3
  nts:
    container_name: nts
    build:
      context: .
      dockerfile: "Dockerfile_nts"
    image: "nts:${VER}"
    privileged: true
    network_mode: "host"
    volumes:
     - "/dev/hugepages:/hugepages"
     - "/var/lib/appliance/nts:/var/lib/nts"
     - "/var/run/docker/netns:/var/run/docker/netns"
     - "/var/run:/var/run"
     - "/proc/1/ns:/var/host_ns"
     - "/sys/class/net:/var/host_net_devices"

  syslog-ng:
    image:  balabit/syslog-ng:3.19.1
    volumes:
      - "./configs/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf:ro"
      - "./certs:/etc/syslog-ng/certs:ro"
      - "/var/log/appliance:/var/log"

    command: "--no-caps"
    extra_hosts:
      - "syslog.community.controller.mec:${REMOTE_SYSLOG_IP}"
    networks:
      net:
        ipv4_address: 192.17.0.5

networks:
  net:
    driver: bridge
    ipam:
     config:
       - subnet: 192.17.0.0/16