# Copyright 2019 Intel Corporation and Smart-Edge.com, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Override global build and deploy server variables here
---
packages_to_install: "jq,moreutils,pixman-devel,autoconf,automake,bison,boost-devel,bridge-utils,cmake,curl,device-mapper-persistent-data,fcgi-devel,flex,gcc-c++,git,glib2-devel,hiredis-devel,jsoncpp-devel,libtool,libvirt,libvirt-devel,lvm2,numactl-devel,openssl-devel,pciutils,pcre-devel,pixman-devel,psmisc,python-httplib2,python-pip,python-websocket-client,vim-common,wget,yum-utils,zlib-devel"
