# Copyright 2019 Intel Corporation and Smart-Edge.com, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
base_path: "{{ '../../../.' | realpath }}"
centos_release: "7.6.1810"
centos_version: "7"
centos_rt_repo_gpg_file: "http://linuxsoft.cern.ch/cern/centos/7/os/x86_64/RPM-GPG-KEY-cern"
centos_rt_repo_file: "http://linuxsoft.cern.ch/cern/centos/{{ centos_version }}/rt/CentOS-RT.repo"
centos_rt_kernel_package_name: "kernel-rt-kvm"
centos_rt_kernel_package_version: "3.10.0-957.12.2.rt56.929.el7.x86_64"
centos_rt_kernel_grub_parameters: "hugepagesz=2M hugepages=50000 intel_iommu=on iommu=pt"
centos_rt_tuned_package_link: "ftp://ftp.icm.edu.pl/vol/rzm3/linux-slc/centos/7.5.1804/os/x86_64/Packages/tuned-2.9.0-1.el7.noarch.rpm"
epel_repository_package_link: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ centos_version }}.noarch.rpm"
packages_to_install: "curl,wget"
dpdk_name: "dpdk-18.11.2"
dpdk_url: "http://fast.dpdk.org/rel/{{ dpdk_name }}.tar.xz"
dpdk_downloaddir: "/temp/dpdk_downloaddir"
dpdk_install_location: "/opt/{{ dpdk_name }}"
dpdk_make_target: "x86_64-native-linuxapp-gcc"
#
go_lang_version: "1.12.4"
go_lang_url: "https://dl.google.com/go/go{{ go_lang_version }}.linux-amd64.tar.gz"
docker_repo_file: "https://download.docker.com/linux/centos/docker-ce.repo"
docker_repo_gpg_file: "https://download.docker.com/linux/centos/gpg"
docker_legacy_packages: "docker,docker-client,docker-client-latest,docker-common,docker-latest,docker-latest-logrotate,docker-logrotate,docker-engine"
docker_packages: "docker-ce,docker-ce-cli,containerd.io"
#
qemu_name: "qemu-3.0.1"
qemu_url: "http://download.qemu.org/{{ qemu_name }}.tar.xz"
qemu_downloaddir: "/temp/qemu_downloaddir"
qemu_target_list: "x86_64-softmmu"
qemu_extract_relative_path: "../temp/qemu/"
#
ovs_version: "2.11.1"
ovs_url: "https://www.openvswitch.org/releases/openvswitch-{{ ovs_version }}.tar.gz"
ovs_downloaddir: "/temp/ovs_downloaddir"
ovs_install_location: "/opt/ovs-{{ ovs_version }}"
ovs_cores_hex: "0x4"
ovs_bridge_name: "br0"
ovs_socket_mem: "1024,0"
dpdk_build: "{{dpdk_install_location}}/{{dpdk_make_target}}/"
ovs:
  enabled: false
#
kubernetes_repo_yum_gpg: "https://packages.cloud.google.com/yum/doc/yum-key.gpg"
kubernetes_repo_rpm_gpg: "https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
kubernetes_packages: "kubelet,kubeadm,kubectl"
kubernetes_sysctl: "/etc/sysctl.d/k8s.conf"
kubernetes_kubeadm_conf: "/usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf"
#
