# Copyright 2019 Intel Corporation and Smart-Edge.com, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Disconnect node from cluster
- include_tasks: ../../../deploy_server/tasks/kubernetes/reset.yml
  when: kubernetes['enabled']

# Cleanup
- include_tasks: ../../common/tasks/docker/remove_images_and_containers.yml
- include_tasks: ../../common/tasks/libvirt/remove_all_vms.yml

# Docker
- include_tasks: ../../../deploy_server/tasks/docker/create_network_config_file.yml
- include_tasks: ../../common/tasks/docker/restart.yml
- include_tasks: ../../common/tasks/docker/import_images_from_location.yml
- include_tasks: ../../../deploy_server/tasks/docker/remove_additional_folder_structure.yml
- include_tasks: ../../../deploy_server/tasks/docker/create_additional_folder_structure.yml

# Certs
- include_tasks: ../../../deploy_server/tasks/certs/remove_certificates_and_keys.yml
- include_tasks: ../../../deploy_server/tasks/certs/create_empty_cert_and_key.yml

# Copy config files
- include_tasks: ../../../deploy_server/tasks/docker/copy_nts_config.yml
  when: not kube_ovn['enabled']
- include_tasks: ../../../deploy_server/tasks/docker/copy_configs_to_appliance.yml
- include_tasks: ../../../deploy_server/tasks/docker/update_appliance_config_files.yml

# Logrotate
- include_tasks: ../../../deploy_server/tasks/os/copy_logrotate_file.yml

# Firewall addons
- include_tasks: ../../common/tasks/docker/add_firewall_rules.yml

# Align libvirt and Docker network settings   
- include_tasks: ../../common/tasks/libvirt/libvirtd_stop.yml
- include_tasks: ../../../deploy_server/tasks/os/virsh_recreate_network_config.yml
- include_tasks: ../../../deploy_server/tasks/docker/create_edgedns_tap.yml
- include_tasks: ../../../deploy_server/tasks/docker/create_network_config_file.yml
- include_tasks: ../../common/tasks/docker/restart.yml
