- name: Get currently running kernel
  shell: uname -r
  changed_when: false
  register: kernel_rt_version_running
- debug:
    msg: "...kernel currently running: {{ kernel_rt_version_running.stdout }} "
