- name: Import Docker appliance image from defined location
  docker_image:
    name: appliance
    #tag: 1.0
    load_path: "{{ docker_image_import_location_path }}/appliance.docker"

- name: Import Docker edgednssvr image from defined location
  docker_image:
    name: edgednssvr
    # tag: 1.0
    load_path: "{{ docker_image_import_location_path }}/edgednssvr.docker"

- name: Import Docker nts image from defined location
  docker_image:
    name: nts
    # tag: 1.0
    load_path: "{{ docker_image_import_location_path }}/nts.docker"
