- name: Check Docker service
  shell: systemctl status docker
  ignore_errors: true
  args:
    warn: false
  register: docker_service_status

- name: Check Docker containers running
  shell: docker ps -a -q
  register: docker_containers_running
  when: docker_service_status.rc == 0

- name: Remove Docker containers
  shell: docker rm -f $(docker ps -a -q)
  when: 
    - docker_service_status.rc == 0
    - docker_containers_running.stdout != ""

- name: Check Docker images
  shell: docker images -q
  register: docker_images_present
  when: docker_service_status.rc == 0
    
- name: Remove Docker images  
  shell: docker rmi -f $(docker images -q)
  when: 
    - docker_service_status.rc == 0
    - docker_images_present.stdout != ''

