# Copyright 2019 Intel Corporation and Smart-Edge.com, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Create Docker folder to save images
  file:
    path: "{{ docker_images_save_path }}"
    state: directory

- debug:
    msg: "Docker images save path set to: {{ docker_images_save_path }}"

- name: Export appliance image to filesystem
  shell: docker save appliance -o "{{ docker_images_save_path }}/appliance.docker"
  when: not kube_ovn['enabled']

- name: Export eaa image to filesystem
  shell: docker save eaa -o "{{ docker_images_save_path }}/eaa.docker"

- name: Export hddlservice image to filesystem
  shell: docker save hddlservice -o "{{ docker_images_save_path }}/hddlservice.docker"
  when: openvino['enabled']

- name: Export edgednssvr image to filesystem
  shell: docker save edgednssvr -o "{{ docker_images_save_path }}/edgednssvr.docker"

- name: Export nts image to filesystem
  shell: docker save nts -o "{{ docker_images_save_path }}/nts.docker"
  when: not kube_ovn['enabled']
