- name: Create dpdk download directory
  become: true
  file:
    path: "{{ dpdk_downloaddir }}"
    state: directory

- name: Download and extract dpdk
  become: true
  unarchive:
    src: "{{ dpdk_url }}"
    dest: "{{ dpdk_downloaddir }}"
    remote_src: yes
    extra_opts: "--strip-components=1"


