# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: interfaceservice
  namespace: openness

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: interfaceservice-csr-requester
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: csr-requester
subjects:
  - kind: ServiceAccount
    name: interfaceservice
    namespace: openness
