# This file is read after global one (/common/defaults.yml)
# You may override default variables here instead of storing then in plays
---
docker_images_save_path: "{{ '../../../dist/.' | realpath }}"
